WTF_CSRF_ENABLED = True
SECRET_KEY = 'shamanyu'

CONNECTION_PROTOCOL = 'http://'
BARCODE_SERVICE_URL = '127.0.0.1'
BARCODE_SERVICE_PORT = ':5001'
BARCODE_SERVICE_ENDPOINT = '/barcode'
WEIGHT_SERVICE_URL = '127.0.0.1'
WEIGHT_SERVICE_PORT = ':5002'
WEIGHT_SERVICE_ENDPOINT = '/weight'
ARM_SERVICE_URL = '127.0.0.1'
ARM_SERVICE_PORT = ':5003'
ARM_SERVICE_ENDPOINT = '/arm'
